### ISSUE TITLE
react-no-multiple-render-methods: TypeError: utils.isES6Component is not a function

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Shopify/web-configs#331]
## Overview

I think this started happening after upgrading eslint-plugin-react from [v7.29.4](https://github.com/jsx-eslint/eslint-plugin-react/releases/tag/v7.29.4) to [v7.30.0](https://github.com/jsx-eslint/eslint-plugin-react/releases/tag/v7.30.0).

```text
ESLint: 8.16.0

TypeError: utils.isES6Component is not a function
Occurred while linting sort-class-members.test.js:13
Rule: "@shopify/react-no-multiple-render-methods"
    at ClassDeclaration (node_modules/@shopify/eslint-plugin/lib/rules/react-no-multiple-render-methods.js:38:32)
    at node_modules/eslint-plugin-react/lib/util/Components.js:275:9
    at Array.forEach (<anonymous>)
    at mergedHandler (node_modules/eslint-plugin-react/lib/util/Components.js:274:11)
    at ruleErrorHandler (node_modules/eslint/lib/linter/linter.js:1114:28)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:326:22)
```

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/EvgenyOrekhov/eslint-config-hardcore

## Labels

- [ ] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by BPScott** [comment]
@alex-page and I ran into a bunch of this in polaris-styleguide too
